version: '3'
services:
  web1:
    build: .
    ports:
     - "8099:80"
    volumes:
     - /tmp/web1:/var/www/html
  web2:
    build: .
    ports:
     - "8089:80"
    volumes:
     - /tmp/web2:/var/www/html
  app1:
    build: 
      context: .
      dockerfile: tomcat-Dockerfile
    ports:
     - "8070:8080"
